#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -ex

npx pretty-quick --staged
npx nx workspace-lint
npx nx format:check
npx nx affected --targets=lint,build,test --configuration=ci
npx playwright install --with-deps
npm run e2e -- --browser=all
