name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  node_version: 18
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Yaml Lint
        run: |
          yamllint --strict -f github \
            -d '{extends: default, rules: {document-start: disable, line-length: {max: 120}, truthy: disable}}' \
            $(git ls-files '*.yaml' '*.yml')
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.node_version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: |
          npm ci
          npx playwright install --with-deps webkit
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - name: Lint, Build, Test
        run: |
          npx playwright install --with-deps webkit
          npm run lint:all
          npm run test:all
          npm run build
      - name: End to End Tests
        run: |
          npm run e2e
