name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  node_version: 26
  npm_config_ignore_scripts: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Yaml Lint
        run: |
          yamllint --strict -f github \
            -d '{extends: default, rules: {document-start: disable, line-length: {max: 120}, truthy: disable}}' \
            $(git ls-files '*.yaml' '*.yml')
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.node_version }}
      - name: Install
        run: npm ci
      - name: Validate commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$TITLE" | npx commitlint --verbose
      - name: Validate peer dependencies
        if: github.event_name == 'pull_request'
        run: |
          node ./scripts/update-peer-dependencies.mjs
          if [[ -n "$(git status --porcelain -- libs/ng-keyboard-sort/package.json)" ]]; then
            echo "Peer dependencies not up to date:"
            git diff --patch -- libs/ng-keyboard-sort/package.json
            exit 1
          fi
      - name: Prep
        run: npx playwright install --with-deps
      - name: Lint
        run: npm run lint:all
      - name: Build
        run: npm run build
      - name: Test
        run: npx ng test -c ci
      - name: End to End Tests
        run: npm run e2e
