name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  node_version: 24
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Yaml Lint
        run: |
          yamllint --strict -f github \
            -d '{extends: default, rules: {document-start: disable, line-length: {max: 120}, truthy: disable}}' \
            $(git ls-files '*.yaml' '*.yml')
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.node_version }}
      - name: Install
        run: npm ci
      - name: Validate commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose
      - name: Prep
        run: npx playwright install --with-deps webkit
      - name: Lint
        run: npm run lint:all
      - name: Build
        run: npm run build
      - name: Test
        run: node ./scripts/test.js
      - name: End to End Tests
        run: npm run e2e
