name: PR Comment
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const sbImage = `https://developer.stackblitz.com/img/open_in_stackblitz.svg`;
            const sbPath = `${{ github.repository }}/tree/${{ github.ref_name }}`;
            const newComment = `
            <!-- ${{ github.workflow }} -->
            [![Open in StackBlitz](${sbImage})](https://stackblitz.com/fork/github/${sbPath})
            `;
            github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            }).then(comments => {
              const comment = comments.data.find(comment => (
                comment.user.login === 'github-actions[bot]'
                && comment.body.includes(`<!-- ${{ github.workflow }} -->`)
              ))
              if (comment) {
                github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id,
                  body: newComment
                })
              } else {
                github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: newComment
                })
              }
            })
