name: Publish

on:
  workflow_dispatch:

env:
  node_version: 18
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.node_version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - name: Build
        run: npm run build:package
      - name: Publish to NPM
        run: |
          VERSION="$(jq -r '.version' package.json)"
          MAJOR_VERSION="$(echo $VERSION | cut -d. -f1)"
          cd dist/ng-keyboard-sort
          npm config set '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}'
          set -x
          npm whoami --registry https://registry.npmjs.org
          npm pkg set "version=${VERSION}"
          npm publish --access public --tag "v${MAJOR_VERSION}-lts"
          npm logout
          npm config delete '//registry.npmjs.org/:_authToken'
      - name: Publish to GitHub Packages
        run: |
          VERSION="$(jq -r '.version' package.json)"
          cd dist/ng-keyboard-sort
          npm config set '@${{ github.repository_owner }}:registry=https://npm.pkg.github.com'
          npm config set '//npm.pkg.github.com/:_authToken=${{secrets.GH_TOKEN}}'
          set -x
          npm whoami --registry https://npm.pkg.github.com
          npm pkg set "version=${VERSION}"
          npm pkg set "name=@${{ github.repository_owner }}/ng-keyboard-sort"
          npm pkg set "publishConfig.registry=https://npm.pkg.github.com"
          npm publish
          npm logout
          npm config delete '@${{ github.repository_owner }}:registry'
          npm config delete '//npm.pkg.github.com/:_authToken'
