name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  node_version: 18
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: '${{ github.ref_name }}'
          changelog-notes-type: 'github'
          package-name: ng-keyboard-sort
          token: ${{ secrets.GH_TOKEN }}
          changelog-types: >
            [
              { "type": "build", "section": "Build System", "hidden": false },
              { "type": "ci", "section": "Continuous Integration", "hidden": false },
              { "type": "chore", "section": "Miscellaneous Chores", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "revert", "section": "Reverts", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false }
            ]
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.node_version }}-${{ hashFiles('**/package-lock.json') }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Install
        run: npm ci
        if: ${{ steps.release.outputs.release_created && steps.cache-node-modules.outputs.cache-hit != 'true' }}
      - name: Build
        run: npm run build:package
        if: ${{ steps.release.outputs.release_created && steps.cache-node-modules.outputs.cache-hit != 'true' }}
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
          cd dist/ng-keyboard-sort
          set -x
          npm version ${{ steps.release.outputs.version }}
          npm publish --access public --tag "v${{ steps.release.outputs.major }}-lts"
          npm dist-tag add "$(jq -r .name package.json)@${{ steps.release.outputs.version }}" latest
          npm logout
      - name: Publish to GitHub Packages
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo 'https://npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
          cd dist/ng-keyboard-sort
          set -x
          npm publish
          npm logout
