name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  node_version: 18
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          default-branch: '${{ github.ref_name }}'
          package-name: ng-keyboard-sort
          token: ${{ secrets.GH_TOKEN }}
          changelog-types: >
            [
              { "type": "build", "section": "Build System", "hidden": false },
              { "type": "ci", "section": "Continuous Integration", "hidden": false },
              { "type": "chore", "section": "Miscellaneous Chores", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "revert", "section": "Reverts", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false }
            ]
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Get node cache
        if: ${{ steps.release.outputs.release_created }}
        id: get-node-cache
        run: |
          ./scripts/node-cache.sh >> $GITHUB_OUTPUT
      - name: Cache node_modules
        if: ${{ steps.release.outputs.release_created }}
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.node_version }}-${{ steps.get-node-cache.outputs.node-cache }}
          restore-keys: '${{ runner.os }}-node-${{ env.node_version }}-'
      - name: Install
        if: ${{ steps.release.outputs.release_created && steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: npm i
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        id: build
        run: |
          npm run build:package
          echo "::set-output name=version::$(cat version.txt)"
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        env:
          VERSION: ${{ steps.build.outputs.version }}
          MAJOR_VERSION: ${{ steps.release.outputs.major }}
        run: |
          cd dist/ng-keyboard-sort
          npm config set '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}'
          set -x
          npm pkg set "version=${VERSION}"
          npm publish --access public --tag "v${MAJOR_VERSION}-lts"
          if [ "${{ github.ref_name }}" = "main" ]; then
            npm dist-tag add "$(jq -r .name package.json)@${VERSION}" latest
          fi
