name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  node_version: 18
  node_cache: ${{ runner.os }}-node-18
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: '${{ github.ref_name }}'
          changelog-notes-type: 'github'
          package-name: ng-keyboard-sort
          token: ${{ secrets.GH_TOKEN }}
          changelog-types: >
            [
              { "type": "build", "section": "Build System", "hidden": false },
              { "type": "ci", "section": "Continuous Integration",
                "hidden": false },
              { "type": "chore", "section": "Miscellaneous Chores",
                "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements",
                "hidden": false },
              { "type": "revert", "section": "Reverts", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring",
                "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false }
            ]
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: gh workflow run publish.yml --ref main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
